### ISSUE TITLE
Do not use a Custom Page Template (such as template-blog.php) 

### ISSUE THREAD

**Issue by dacopan** [Codeinwp/Parallax-One#390]
Hi, based on wordpress documentation: https://codex.wordpress.org/Creating_a_Static_Front_Page
Use only the home.php template file for the blog posts index. **Do not use a Custom Page Template (such as template-blog.php)** for two reasons:
- When the static front page feature is configured properly, WordPress will not use a Custom Page Template to display the blog posts index, even if a Custom Page Template is assigned to the page designated as the "Posts page". WordPress will only use either home.php or index.php.
- When the Custom Page Template is assigned to a static page other than the one designated as the "Posts page," the blog posts index loop pagination will not work properly.

**Comment by ineagu** [comment]
Hey @dacopan,

Thanks a lot for the issues raised and pull request, however this in particular is a complex subject : 

Since there is no better solution in core, in order to make things really easy for users, we display the custom front-page when latest-post is selected, which means that we needed to create a custom blog template in case you want a blog displayed.

The current process of setting a front-page in WordPress is so complex ( create new page ->set template-> set as frontpage ) for new users and is just an extra useless step since 99% of ParallaxOne users don't use blog as frontpage.
