### ISSUE TITLE
 Undefined property: stdClass::$link

### ISSUE THREAD

**Issue by dacopan** [Codeinwp/Parallax-One#393]
PHP Notice:  Undefined property: stdClass::$link in Parallax-One/sections/parallax_one_our_services_section.php on line 74

$parallax_one_services default values missing link property

**Comment by dacopan** [comment]
when theme install or when user remove link

**Comment by ineagu** [comment]
@rodica-andronache .

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I can't replicate this. Can you please check?

**Comment by dacopan** [comment]
You missing default 'link' atribute in customize.php and in services section deafult content....

So when install and active theme in first time (clean wordpress install) php show this error....

**Comment by rodica-andronache** [comment]
@cristian-ungureanu 

you used isser instead of isset in one instance, please be more careful when testing as it was causing the site to not load anymore :)
also, by checking if a variable is !empty , you don't need to also check if isset . you can read more about this here http://php.net/manual/en/function.empty.php
